# Generated by Django 4.0.5 on 2022-06-19 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.IntegerField(max_length=4, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=30)),
                ('project_amount', models.FloatField(max_length=20)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(max_length=4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('user_designation', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('expense_id', models.IntegerField(max_length=4, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('amount', models.FloatField(max_length=20)),
                ('date', models.DateField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.project')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.user')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.IntegerField(max_length=4, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('company_phone', models.IntegerField(max_length=15)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.project')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.user')),
            ],
        ),
    ]
